#!/usr/bin/env bash
cd /Users/lbut/galen/reports/img_comp/2018_03_18_22_43_38/www.vr.de\\privatkunden.html/desktop/
/usr/local/bin/convert source_000001.png target_000001.png \( -clone 0 -clone 1 -compose minus -composite -threshold 0 \) -delete 1 -alpha off -compose copy_opacity -composite diff.png
/usr/local/bin/convert diff.png -background white -flatten diff1.png
/usr/local/bin/convert diff.png -fill white -draw 'color 0,0 reset' back.png
/usr/local/bin/compare -compose src diff1.png back.png -highlight-color  cyan diff2.png
