#!/usr/bin/env bash

cd /Users/lbut/galen/

timeStamp=$(date '+%Y_%m_%d_%H_%M_%S');

if [ ! -d "./reports/gdtf5/${timeStamp}" ]; then
mkdir "./reports/gdtf5/${timeStamp}";
fi

open -a Terminal.app "./bash/startSelenium"
#open -a Terminal.app "./bash/startAppiumiOS"
#open -a Terminal.app "./bash/startAppiumAndroid"

sleep 5

galen test ./testconfig/gdtf5.test --htmlreport ./reports/gdtf5/${timeStamp} --parallel-tests 4

#wait
#killall Terminal