#!/usr/bin/env bash

cd /Users/lilia/Downloads/galen-bin-2.3.0/

timeStamp=$(date '+%Y_%m_%d_%H_%M_%S');

if [ ! -d "./reports/katf5/${timeStamp}" ]; then
mkdir "./reports/katf5/${timeStamp}";
fi

open -a Terminal.app "./bash/startSelenium"
open -a Terminal.app "./bash/startAppiumiOS"
open -a Terminal.app "./bash/startAppiumAndroid"

sleep 5

galen test ./testconfig/katf9.test --htmlreport ./reports/katf9/${timeStamp} --parallel-tests 4
wait
killall Terminal