#!/usr/bin/env bash

cd /Users/lilia/Downloads/galen-bin-2.3.0/

timeStamp=$(date '+%Y_%m_%d_%H_%M_%S');

open -a Terminal.app "./bash/startSelenium"
open -a Terminal.app "./bash/startAppiumiOS"
open -a Terminal.app "./bash/startAppiumAndroid"

sleep 5

galen test ./testconfig/katf15_mob.test --htmlreport ./reports/katf15/${timeStamp} --parallel-tests 4
wait
killall Terminal